### PR TITLE
added support for debian 11

### PR DESCRIPTION
**Pull request by FrankreedX**

### CODE REVIEW

**Comment by FrankreedX** [comment]
[Debian 11: osl-postfix](https://trello.com/c/wXJNNUny/2585-debian-11-osl-postfix)

**Review by ramereth — APPROVED** [review]
Please do a patch bump.

**Review by ramereth — CHANGES_REQUESTED** [review]
Don't bump it in this PR, we do this automatically!

**Review by ramereth — APPROVED** [review]

**Comment by FrankreedX** [comment]
!bump patch ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v2.1.2.  Have a nice day!

**Pull request merged**
