### PR TITLE
Bump postfix cookbook to 5.4.0

### PR DESCRIPTION
**Pull request by zimmerry**

### CODE REVIEW

**Comment by zimmerry** [comment]
[CentOS 8: osl-mailman](https://trello.com/c/Ij5sPrgl/1907-centos-8-osl-mailman)

**Review by ramereth — APPROVED** [review]
Please do a patch bump.

**Comment by zimmerry** [comment]
!bump patch ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v1.2.2.  Have a nice day!

**Pull request merged**
